version: '3'
services:
  backend:
    build:
      context: sonarQuest-backend/
      dockerfile: Docker/Dockerfile
    command: -DsimulateSonarServer=true
    ports:
     - "8080:8080"
    volumes:
     - ./h2data:/h2dir
  frontend:
    build:
      context: sonarQuest-frontend/
      dockerfile: Docker/Dockerfile
    ports:
      - "4200:4200"
